### PR TITLE
fix: handle different vault injection cases

### LINKED ISSUE #68: Handle different Vault provider injection cases
## Overview
Currently, when an env variable value contains `vault:` prefix, it is handled by Vault provider. However, Vault injector can inject secrets in many different ways (shown below). `getProviderPath` should be extended to support proper classification of envs for Vault provider. 

Since we heavily rely on `github.com/bank-vaults/internal` package, it would be useful to add a public method to `injector` package, something like `IsValidVaultEnv` (bad name, we can think of it later) that should return true when a given env value can be processed by `InjectSecretsFromVault` or `InjectSecretsFromVaultPath`.

**Supported Vault injector env references**
From https://github.com/bank-vaults/internal/blob/1d4670005e01baaa08bac7e17d0876d444d3286b/injector/injector_test.go#L92-L101
```go
references := map[string]string{
	"ACCOUNT_PASSWORD_1":              "vault:secret/data/account#password#1",
	"ACCOUNT_PASSWORD":                "vault:secret/data/account#password",
	"TRANSIT_SECRET":                  `>>vault:transit/decrypt/mykey#${.plaintext | b64dec}#{"ciphertext":"` + ciphertext + `"}`,
	"ROOT_CERT":                       ">>vault:pki/root/generate/internal#certificate",
	"ROOT_CERT_CACHED":                ">>vault:pki/root/generate/internal#certificate",
	"INLINE_SECRET":                   "scheme://${vault:secret/data/account#username}:${vault:secret/data/account#password}@127.0.0.1:8080",
	"INLINE_SECRET_EMBEDDED_TEMPLATE": "scheme://${vault:secret/data/account#username}:${vault:secret/data/account#${.password | urlquery}}@127.0.0.1:8080",
	"INLINE_DYNAMIC_SECRET":           "${>>vault:pki/root/generate/internal#certificate}__${>>vault:pki/root/generate/internal#certificate}",
}
```

### PR DESCRIPTION
**Pull request by csatib02**
## Overview

- The `injector` already utilizes a bunch of things, to detect vault secret references.
- On the side of `secret-init` it's sufficient if we use a regex to detect `vault:something/something/...` like substrings in the env-values, since it won't mistake `vault` like env-values for vault references, and if somehow a non-vault reference would be detected, the injector would just ignore it.
- Added an e2e test case to test different injection scenarios.

Fixes #68

### CODE REVIEW

File: env_store.go [hunk 1]
```diff
@@ -157,7 +158,10 @@ func getProviderPath(path string) (string, string) {
 		var fileProviderName = file.ProviderName
 		return fileProviderName, strings.TrimPrefix(path, "file:")
 	}
-	if strings.HasPrefix(path, "vault:") {
+	// If the path contains the "vault:" substring it is most probably a vault path
+	// otherwise the injector will not process it
+	re := regexp.MustCompile(`(vault:\w+)(\/\w+)`)
```
Comment (ramizpolic) [inline env_store.go:163]: Can we use a more generic regexp here such as `(vault:)(.*)#(.*)` to make it more consistent? This might not catch all the cases, while the false-positives will be handled by the internal package anway.

File: env_store.go [hunk 2]
```diff
@@ -157,7 +158,10 @@ func getProviderPath(path string) (string, string) {
 		var fileProviderName = file.ProviderName
 		return fileProviderName, strings.TrimPrefix(path, "file:")
 	}
-	if strings.HasPrefix(path, "vault:") {
+	// If the path contains the "vault:" substring it is most probably a vault path
```
Comment (ramizpolic) [inline env_store.go:161]:
```suggestion
	// If the path contains some string formatted as "vault:{STR}#{STR}" it is most probably a vault path
```

**Review by ramizpolic — CHANGES_REQUESTED** [review]

**Comment by ramizpolic** [comment]
The test scenario in `env_store_test.go` could be a bit changed to set envs itself, for example rather than using `createEnvsForProvider` helper function, we could set envs in the test cases explicitly. 
Note that the actual file is not needed for this specific test case since the test is only extracting data from envs.
I have added three cases to cover, just make sure to fill with the expected data
```go
func TestEnvStore_GetProviderPaths(t *testing.T) {
	tests := []struct {
		name      string
		envs 	  map[string]string
		wantPaths map[string][]string
	}{
		{
			name: "file provider",
			envs: map[string]string{
				"AWS_SECRET_ACCESS_KEY_ID": "file:FILEPATH",
			}
			wantPaths: map[string][]string{
				"file": {
					"FILEPATH"
				},
			},
		},
		{
			name: "vault provider",
			envs: map[string]string{
				// Add all the envs from https://github.com/bank-vaults/internal/blob/1d4670005e01baaa08bac7e17d0876d444d3286b/injector/injector_test.go#L92-L101
			}
			wantPaths: map[string][]string{
				"vault": {
					// fill expected
				},
			},
		},
		{
			name: "multi provider",
			envs: map[string]string{
				"AWS_SECRET_ACCESS_KEY_ID": "file:FILEPATH",
				"MYSQL_PASSWORD": "vault:secret/data/test/mysql#MYSQL_PASSWORD",
				"AWS_SECRET_ACCESS_KEY: "vault:secret/data/test/aws#AWS_SECRET_ACCESS_KEY",
			}
			wantPaths: map[string][]string{
				"vault": {
					// fill expected
				},
				"file": {
					// fill expected
				},
			},
		},
	}

	for _, tt := range tests {
		ttp := tt
		t.Run(ttp.name, func(t *testing.T) {
			// prepare envs
			for envKey, envVal := range ttp.envs {
				os.Setenv(envKey, envVal)
				t.Cleanup(func() {
					os.Unsetenv(envKey)
				})
			}

			paths := NewEnvStore().GetProviderPaths()

			for key, expectedSlice := range ttp.wantPaths {
				actualSlice, ok := paths[key]
				assert.True(t, ok, "Key not found in actual paths")
				assert.ElementsMatch(t, expectedSlice, actualSlice, "Slices for key %s do not match", key)
			}
		})
	}
}
```

File: provider/vault/config_test.go [hunk 3]
```diff
@@ -112,7 +112,9 @@ func TestConfig(t *testing.T) {
 			for envKey, envVal := range ttp.env {
 				os.Setenv(envKey, envVal)
 			}
-			defer os.Clearenv()
+			t.Cleanup(func() {
+				defer os.Clearenv()
```
Comment (ramizpolic) [inline provider/vault/config_test.go:116]: defer is not needed here

File: provider/file/config_test.go [hunk 4]
```diff
@@ -47,7 +47,9 @@ func TestConfig(t *testing.T) {
 			for envKey, envVal := range ttp.env {
 				os.Setenv(envKey, envVal)
 			}
-			defer os.Clearenv()
+			t.Cleanup(func() {
+				defer os.Clearenv()
```
Comment (ramizpolic) [inline provider/file/config_test.go:51]: defer not needed

File: env_store_test.go [hunk 5]
```diff
@@ -25,44 +25,76 @@ import (
...
 		t.Run(ttp.name, func(t *testing.T) {
-			createEnvsForProvider(ttp.addvault, secretFile)
-			envStore := NewEnvStore()
-			paths := envStore.GetProviderPaths()
+			// prepare envs
+			for envKey, envVal := range ttp.envs {
+				os.Setenv(envKey, envVal)
+			}
+			t.Cleanup(func() {
+				defer os.Clearenv()
```
Comment (ramizpolic) [inline env_store_test.go:94]: defer not needed

**Review by ramizpolic — CHANGES_REQUESTED** [review]

**Review by ramizpolic — APPROVED** [review]
great work! :shipit:
