### PR TITLE
fix: remove vault_addr workaround

### LINKED ISSUE #112: Remove openBao workaround when its been released
There is a workaround applied in `provider/bao/config.go` and in `env_store.go`, remove those when, openBao utilizes BAO_ADDR, instead of VAULT_ADDR

### PR DESCRIPTION
**Pull request by csatib02**
Fixes #112

### CODE REVIEW

File: env_store.go [hunk 1]
```diff
@@ -107,20 +107,7 @@ func (s *EnvStore) GetSecretReferences() map[string][]string {
 // The secrets from each provider are then placed into a single slice.
 func (s *EnvStore) LoadProviderSecrets(ctx context.Context, providerPaths map[string][]string) ([]provider.Secret, error) {
 	var providerSecrets []provider.Secret
-	// Workaround for openBao
-	// Remove once openBao uses BAO_ADDR in their client, instead of VAULT_ADDR
```
Comment (cipherboy) [inline env_store.go:111]: fwiw, we support both `BAO_ADDR` and `VAULT_ADDR`, but prefer `BAO_ADDR` if present. This is true of all `BAO_` prefixed variables, but not true of direct headers (`X-Vault-*` are still used but `X-OpenBao-*` aren't defined and we've added new headers with the `X-Vault-*` prefix).
